# Project settings
project: default
custom: '1' # string appended to experiment name

# Model parameters
hyperbolic: false
embedding_dim: 2
hyp_layers: 2

# Training parameters
num_epochs: 8
num_trajectories: 10000 
batch_size: 64
num_negatives: 64
max_steps: 100
num_workers: 8
learning_rate: 0.001

# Maze settings
maze_type: blank 
gamma: 0.1

# Experiment tracking
order_name: ''
eval_trials: 10
temperature: 0.1
architecture: MLP
