# Project settings
project: temp
custom: '1' # string appended to experiment name

# Model parameters
hyperbolic: false
embedding_dim: 8
hyp_layers: 2

# Training parameters
num_epochs: 512
num_trajectories: 50000
batch_size: 512
num_negatives: 64
max_steps: 100
num_workers: 24
learning_rate: 0.001

# Maze settings
maze_type: blocker
gamma: 0.1

# Experiment tracking
order_name: ''
eval_trials: 10
temperature: 0.1
architecture: MLP
