# Project settings
project: discrete_maze
custom: '' # string appended to experiment name

# Model parameters
env: 'maze'
maze_type: 'nested_pyramid'
hyperbolic: true
embedding_dim: 4
curvature: 1.0 # absolute value of curvature (always negative)
learnable_curvature: true

# Training parameters
num_epochs: 512
num_trajectories: 25000
batch_size: 512
num_negatives: 128
max_steps: 100 
num_workers: 24
learning_rate: 0.01

# Tree settings
depth: 7
branching_factor: 2
gamma: 0.1

# Experiment tracking
order_name: ''
eval_trials: 100
temperature: 0.1
architecture: MLP
symmetric: false
