# Project settings
project: sethyp
custom: '3' # string appended to experiment name

# Model parameters
hyperbolic: true
embedding_dim: 2
hyp_layers: 2

# Training parameters
num_epochs: 512
num_trajectories: 10000
batch_size: 128
num_negatives: 64
max_steps: 100
num_workers: 24
learning_rate: 0.001

# Maze settings
maze_type: blocker
gamma: 0.1

# Experiment tracking
order_name: ''
eval_trials: 10
temperature: 0.1
architecture: MLP
